POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ

{
    "title": "My name is title",
    "author": "I am the author",
    "url": "This is my url",
    "likes": 100,
    "user": "kaip"
}